function quadrotor_3d_metrics_gui(z_ref, x0, T)
    % create main figure
    f = figure( ...
        'Position',       [100, 100, 1150, 750], ...
        'Name',           'Quadrotor 1D Control + Metrics', ...
        'Color',          [1 1 1] );

    % axes for plots
    ax1 = axes('Parent',f,'Units','pixels','Position',[70, 450, 380, 220]);
    ax3 = axes('Parent',f,'Units','pixels','Position',[70, 130, 400, 250]);
    ax2 = axes('Parent',f,'Units','pixels','Position',[580, 280, 500, 400]);

    %% Kp slider + label + value display
    uicontrol( ...
        'Parent',        f, ...
        'Style',         'text', ...
        'Units',         'pixels', ...
        'Position',      [150, 70, 40, 20], ...
        'String',        'Kp', ...
        'FontWeight',    'bold', ...
        'HorizontalAlignment','right' );
    kp_slider = uicontrol( ...
        'Parent',        f, ...
        'Style',         'slider', ...
        'Units',         'pixels', ...
        'Min',           0, ...
        'Max',           50, ...
        'Value',         10, ...
        'Position',      [200, 70, 200, 20], ...
        'Tag',           'KpSlider', ...
        'TooltipString', 'Proportional gain (Kp)' );
    kp_val_txt = uicontrol( ...
        'Parent',        f, ...
        'Style',         'text', ...
        'Units',         'pixels', ...
        'Position',      [420, 70, 50, 20], ...
        'HorizontalAlignment','left' );

    %% Kv slider + label + value display
    uicontrol( ...
        'Parent',        f, ...
        'Style',         'text', ...
        'Units',         'pixels', ...
        'Position',      [150, 40, 40, 20], ...
        'String',        'Kv', ...
        'FontWeight',    'bold', ...
        'HorizontalAlignment','right' );
    kv_slider = uicontrol( ...
        'Parent',        f, ...
        'Style',         'slider', ...
        'Units',         'pixels', ...
        'Min',           0, ...
        'Max',           50, ...
        'Value',         5, ...
        'Position',      [200, 40, 200, 20], ...
        'Tag',           'KvSlider', ...
        'TooltipString', 'Derivative gain (Kv)' );
    kv_val_txt = uicontrol( ...
        'Parent',        f, ...
        'Style',         'text', ...
        'Units',         'pixels', ...
        'Position',      [420, 40, 50, 20], ...
        'HorizontalAlignment','left' );

    %% metrics display
    metric_txt = uicontrol( ...
        'Parent',           f, ...
        'Style',            'edit', ...            % supports multiple lines
        'Units',            'pixels', ...
        'Position',         [580, 50, 500, 60], ...
        'FontSize',         11, ...
        'HorizontalAlignment','left', ...
        'BackgroundColor',  get(f,'Color'), ...    % blend with figure
        'Enable',           'inactive', ...        % read‐only
        'Max',              2 );                   %

    %% common callback for both sliders
    function slider_cb(~,~)
        kp = get(kp_slider,'Value');
        kv = get(kv_slider,'Value');
        set(kp_val_txt,'String',sprintf('%.2f',kp));
        set(kv_val_txt,'String',sprintf('%.2f',kv));

        % now call your plotting/metrics function
        update_plot_gui( ...
            kp_slider, kv_slider, kp_val_txt, kv_val_txt, ...
            ax1, ax3, ax2, metric_txt, ...
            z_ref, x0, T );
    end

   % Assign callback with parameters using anonymous function
    kp_slider.Callback = @(~, ~) update_plot_gui(kp_slider, kv_slider, kp_val_txt, kv_val_txt, ...
                                                  ax1, ax3, ax2, metric_txt,z_ref,x0,T);
    kv_slider.Callback = kp_slider.Callback;  % Same callback

    % Initial plot
    kp_slider.Callback();
end
